plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    alias libs.plugins.lombok
}

group = 'com.github.bitsoex'
version = '4.4.0'

description = "bitso-java"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}

repositories {
    maven {
        url = "https://repo.maven.apache.org/maven2/"
    }
}

dependencies {
    api libs.httpclient5
    api libs.json
    api libs.netty
    api libs.slf4j.api

    testImplementation libs.junit
    testImplementation 'org.junit.platform:junit-platform-launcher'
    testImplementation libs.mockito.jupiter
    testRuntimeOnly libs.slf4j.simple
}

test.useJUnitPlatform()

java {
    withJavadocJar()
    withSourcesJar()
}

// To specify a license in the pom:
publishing {
    publications {
        maven(MavenPublication) {
            pom {
                name = 'Bitso REST API Client'
                licenses {
                    license {
                        name = 'The MIT License (MIT)'
                        url = 'https://github.com/bitsoex/bitso-java/blob/master/LICENSE'
                        distribution = 'repo'
                    }
                }
            }
            from components.java
        }
    }
}
