[versions]
slf4j = "2.0.20"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jakarta-annotation = "jakarta.annotation:jakarta.annotation-api:3.0.0"
json = "org.json:json:20260814"
netty = "io.netty:netty-all:4.2.18.Final"
junit = "org.junit.jupiter:junit-jupiter:5.14.4"
mockito-jupiter = "org.mockito:mockito-junit-jupiter:5.24.0"

[plugins]
lombok = "io.freefair.lombok:9.7.0"
